---
title: "Bienvenue"
description: "scheint, als hättest du dich auf meinen Blog verirrt. Hier halte ich fest, was Strava irgendwann verschluckt und nicht zeigt: Bikepackingtouren, Träume und Projekte."
output:
  distill::distill_article:
    css: "strapless.css"


---

<svg aria-hidden="true" role="img" viewBox="0 0 512 512" style="height:14px;width:14px;vertical-align:-0.125em;margin-left:auto;margin-right:auto;font-size:inherit;fill:#ededeb;overflow:visible;position:relative;"><path d="M352 320c88.4 0 160-71.6 160-160c0-15.3-2.2-30.1-6.2-44.2c-3.1-10.8-16.4-13.2-24.3-5.3l-76.8 76.8c-3 3-7.1 4.7-11.3 4.7H336c-8.8 0-16-7.2-16-16V118.6c0-4.2 1.7-8.3 4.7-11.3l76.8-76.8c7.9-7.9 5.4-21.2-5.3-24.3C382.1 2.2 367.3 0 352 0C263.6 0 192 71.6 192 160c0 19.1 3.4 37.5 9.5 54.5L19.9 396.1C7.2 408.8 0 426.1 0 444.1C0 481.6 30.4 512 67.9 512c18 0 35.3-7.2 48-19.9L297.5 310.5c17 6.2 35.4 9.5 54.5 9.5zM80 456c-13.3 0-24-10.7-24-24s10.7-24 24-24s24 10.7 24 24s-10.7 24-24 24z"/>



```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(file.path("R", "functions.R"))
library(distilltools)
library(tidyverse)
```

```{r projects, echo=FALSE, layout="l-body-outset"}
projects <- readr::read_csv2(here::here("content", "overview.csv"))
projects %>% 
  bs4cards::cards(
    title = title,
    text = description,
    link = url,
    image = src,
    label_colour = "#ffffff",
    tags = paste("All;", tags),
    footer = tags,
    border_radius = 5
  )
```